from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from shellsense.utils.logging import get_logger

logger = get_logger(__name__)


@dataclass
class TemplateInfo:
    name: str
    description: str
    category: str
    tags: list[str] = field(default_factory=list)
    version: str = "1.0.0"
    output_extension: str = ".sh"
    content: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "description": self.description,
            "category": self.category,
            "tags": self.tags,
            "version": self.version,
            "output_extension": self.output_extension,
            "content": self.content,
            "metadata": self.metadata,
        }


class TemplateLibrary:
    def __init__(self) -> None:
        self._templates: dict[str, TemplateInfo] = {}
        self._register_builtins()

    def _register_builtins(self) -> None:
        builtins: list[TemplateInfo] = [
            TemplateInfo(
                name="backup-script",
                description="Create a file/directory backup script with rotation",
                category="bash",
                tags=["backup", "system", "cron"],
                output_extension=".sh",
                content="""#!/usr/bin/env bash
# {name} - {description}
# Generated by ShellSense AI
set -euo pipefail

BACKUP_SRC="{source}"
BACKUP_DST="{destination}"
BACKUP_NAME="{name}"
RETENTION_DAYS={retention_days}
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
BACKUP_FILE="${{BACKUP_DST}}/${{BACKUP_NAME}}_${{TIMESTAMP}}.tar.gz"

mkdir -p "$BACKUP_DST"

echo "Creating backup: $BACKUP_FILE"
tar -czf "$BACKUP_FILE" -C "$(dirname "$BACKUP_SRC")" "$(basename "$BACKUP_SRC")"

echo "Cleaning backups older than $RETENTION_DAYS days..."
find "$BACKUP_DST" -name "${{BACKUP_NAME}}_*.tar.gz" -mtime +$RETENTION_DAYS -delete

echo "Backup complete: $BACKUP_FILE"
""",
                metadata={
                    "fields": ["source", "destination", "name", "retention_days"]
                },
            ),
            TemplateInfo(
                name="log-rotation",
                description="Generate a log rotation script",
                category="bash",
                tags=["logs", "system", "maintenance"],
                output_extension=".sh",
                content="""#!/usr/bin/env bash
# {name} - Log Rotation Script
# Generated by ShellSense AI
set -euo pipefail

LOG_DIR="{log_dir}"
LOG_PATTERN="{pattern}"
MAX_SIZE={max_size_mb}M
RETENTION_COUNT={retention_count}

for logfile in "$LOG_DIR"/$LOG_PATTERN; do
    [ -f "$logfile" ] || continue
    size=$(stat -c%s "$logfile" 2>/dev/null || stat -f%z "$logfile" 2>/dev/null)
    size_mb=$((size / 1048576))
    if [ "$size_mb" -gt "${{MAX_SIZE%%M}}" ]; then
        echo "Rotating: $logfile (${{size_mb}}MB)"
        timestamp=$(date +%Y%m%d_%H%M%S)
        mv "$logfile" "${{logfile}}.$timestamp"
        gzip "${{logfile}}.$timestamp"
    fi
done

find "$LOG_DIR" -name "${{LOG_PATTERN}}.*.gz" -type f | sort | head -n -"$RETENTION_COUNT" | while read old; do
    rm "$old"
    echo "Removed old log: $old"
done

echo "Log rotation complete"
""",
                metadata={
                    "fields": ["log_dir", "pattern", "max_size_mb", "retention_count"]
                },
            ),
            TemplateInfo(
                name="disk-cleanup",
                description="Generate a disk cleanup script",
                category="bash",
                tags=["cleanup", "system", "maintenance"],
                output_extension=".sh",
                content="""#!/usr/bin/env bash
# {name} - Disk Cleanup Script
# Generated by ShellSense AI
set -euo pipefail

THRESHOLD_PCT={threshold_pct}
CLEANUP_DIRS=({cleanup_dirs})

check_disk_usage() {
    df "$1" | awk 'NR==2 {{print $5}}' | sed 's/%//'
}

for dir in "${{CLEANUP_DIRS[@]}}"; do
    if [ ! -d "$dir" ]; then
        echo "Skipping non-existent: $dir"
        continue
    fi
    usage=$(check_disk_usage "$dir")
    if [ "$usage" -gt "$THRESHOLD_PCT" ]; then
        echo "WARNING: $dir is at ${usage}% usage (threshold: ${THRESHOLD_PCT}%)"
    fi
done

# Package manager cache cleanup
if command -v apt-get &>/dev/null; then
    echo "Cleaning apt cache..."
    apt-get clean
    apt-get autoremove --purge -y 2>/dev/null || true
fi

# Journal cleanup
if command -v journalctl &>/dev/null; then
    echo "Cleaning journal logs..."
    journalctl --vacuum-time=7d 2>/dev/null || true
fi

# Temp files
echo "Cleaning /tmp..."
find /tmp -type f -atime +7 -delete 2>/dev/null || true

echo "Disk cleanup complete"
""",
                metadata={"fields": ["threshold_pct", "cleanup_dirs"]},
            ),
            TemplateInfo(
                name="package-update",
                description="Generate a system package update script",
                category="bash",
                tags=["packages", "system", "maintenance"],
                output_extension=".sh",
                content="""#!/usr/bin/env bash
# {name} - Package Update Script
# Generated by ShellSense AI
set -euo pipefail

LOG_FILE="{log_file:-/var/log/packages_update.log}"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "$LOG_FILE"
}

if command -v apt-get &>/dev/null; then
    log "Updating apt package lists..."
    apt-get update >> "$LOG_FILE" 2>&1
    log "Upgrading packages..."
    apt-get upgrade -y >> "$LOG_FILE" 2>&1
    log "Upgrading distribution..."
    apt-get dist-upgrade -y >> "$LOG_FILE" 2>&1 || true
elif command -v dnf &>/dev/null; then
    log "Updating dnf packages..."
    dnf upgrade -y >> "$LOG_FILE" 2>&1
elif command -v yum &>/dev/null; then
    log "Updating yum packages..."
    yum update -y >> "$LOG_FILE" 2>&1
elif command -v pacman &>/dev/null; then
    log "Updating pacman packages..."
    pacman -Syu --noconfirm >> "$LOG_FILE" 2>&1
fi

if command -v snap &>/dev/null; then
    log "Updating snap packages..."
    snap refresh >> "$LOG_FILE" 2>&1 || true
fi

if command -v flatpak &>/dev/null; then
    log "Updating flatpak packages..."
    flatpak update -y >> "$LOG_FILE" 2>&1 || true
fi

log "Package update complete"
""",
                metadata={"fields": ["log_file"]},
            ),
            TemplateInfo(
                name="health-check",
                description="Generate a system health check script",
                category="bash",
                tags=["monitoring", "system", "diagnostics"],
                output_extension=".sh",
                content="""#!/usr/bin/env bash
# {name} - System Health Check
# Generated by ShellSense AI
set -euo pipefail

ALERT_CPU={alert_cpu}
ALERT_MEM={alert_mem}
ALERT_DISK={alert_disk}
CHECK_SERVICES=({check_services})

echo "=== System Health Check ==="
echo "Hostname: $(hostname)"
echo "Date: $(date)"
echo "Uptime: $(uptime -p)"
echo ""

echo "=== CPU Usage ==="
cpu_usage=$(top -bn1 | grep "Cpu(s)" | awk '{print $2}' | cut -d. -f1)
echo "CPU: ${cpu_usage:-0}%"
if [ "${cpu_usage:-0}" -gt "$ALERT_CPU" ] 2>/dev/null; then
    echo "WARNING: CPU usage above ${ALERT_CPU}%"
fi

echo ""
echo "=== Memory Usage ==="
free -h
mem_usage=$(free | grep Mem | awk '{print ($3/$2) * 100.0}' | cut -d. -f1)
if [ "${mem_usage:-0}" -gt "$ALERT_MEM" ] 2>/dev/null; then
    echo "WARNING: Memory usage above ${ALERT_MEM}%"
fi

echo ""
echo "=== Disk Usage ==="
df -h | grep -E '^/dev/' || df -h /
while read -r line; do
    pct=$(echo "$line" | awk '{print $5}' | sed 's/%//')
    mount=$(echo "$line" | awk '{print $6}')
    if [ "$pct" -gt "$ALERT_DISK" ] 2>/dev/null; then
        echo "WARNING: $mount is at ${pct}% usage"
    fi
done < <(df -h | grep -E '^/dev/')

echo ""
echo "=== Service Status ==="
for svc in "${CHECK_SERVICES[@]}"; do
    if systemctl is-active --quiet "$svc" 2>/dev/null; then
        echo "  [OK] $svc"
    else
        echo "  [FAIL] $svc"
    fi
done

echo ""
echo "=== Last Logins ==="
last -5 2>/dev/null || echo "No login history available"

echo ""
echo "Health check complete"
""",
                metadata={
                    "fields": ["alert_cpu", "alert_mem", "alert_disk", "check_services"]
                },
            ),
            TemplateInfo(
                name="systemd-service",
                description="Generate a systemd service unit file",
                category="systemd",
                tags=["service", "systemd", "daemon"],
                output_extension=".service",
                content="""[Unit]
Description={description}
After={after}
Requires={requires}
Documentation={documentation}

[Service]
Type={type}
User={user}
Group={group}
WorkingDirectory={working_directory}
ExecStart={exec_start}
ExecReload={exec_reload}
Restart={restart}
RestartSec={restart_sec}
EnvironmentFile={env_file}
StandardOutput=journal
StandardError=journal
LimitNOFILE={limit_nofile}

[Install]
WantedBy={wanted_by}
""",
                metadata={
                    "fields": [
                        "description",
                        "after",
                        "requires",
                        "documentation",
                        "type",
                        "user",
                        "group",
                        "working_directory",
                        "exec_start",
                        "exec_reload",
                        "restart",
                        "restart_sec",
                        "env_file",
                        "limit_nofile",
                        "wanted_by",
                    ],
                    "defaults": {
                        "after": "network.target",
                        "type": "simple",
                        "restart": "on-failure",
                        "restart_sec": "5",
                        "limit_nofile": "65535",
                        "wanted_by": "multi-user.target",
                    },
                },
            ),
            TemplateInfo(
                name="systemd-timer",
                description="Generate a systemd timer unit file",
                category="systemd",
                tags=["timer", "systemd", "scheduling"],
                output_extension=".timer",
                content="""[Unit]
Description={description}
Requires={requires}

[Timer]
OnCalendar={on_calendar}
OnBootSec={on_boot_sec}
OnUnitActiveSec={on_unit_active_sec}
Unit={unit}
Persistent={persistent}
RandomizedDelaySec={randomized_delay}

[Install]
WantedBy={wanted_by}
""",
                metadata={
                    "fields": [
                        "description",
                        "requires",
                        "on_calendar",
                        "on_boot_sec",
                        "on_unit_active_sec",
                        "unit",
                        "persistent",
                        "randomized_delay",
                        "wanted_by",
                    ],
                    "defaults": {
                        "persistent": "true",
                        "randomized_delay": "5min",
                        "wanted_by": "timers.target",
                    },
                },
            ),
            TemplateInfo(
                name="dockerfile",
                description="Generate a Dockerfile for containerized applications",
                category="docker",
                tags=["docker", "container", "build"],
                output_extension="Dockerfile",
                content="""# {name} - {description}
# Generated by ShellSense AI
FROM {base_image}:{base_tag}

LABEL maintainer="{maintainer}" \\
      description="{description}"

{arg_section}
ENV DEBIAN_FRONTEND=noninteractive \\
    {env_vars}

RUN apt-get update && apt-get install -y --no-install-recommends \\
    {packages} \\
    && rm -rf /var/lib/apt/lists/*

{extra_commands}

WORKDIR {workdir}

{copy_section}

EXPOSE {ports}

{entrypoint_section}
""",
                metadata={
                    "fields": [
                        "name",
                        "description",
                        "base_image",
                        "base_tag",
                        "maintainer",
                        "packages",
                        "workdir",
                        "ports",
                        "env_vars",
                        "arg_section",
                        "extra_commands",
                        "copy_section",
                        "entrypoint_section",
                    ],
                    "defaults": {
                        "base_image": "ubuntu",
                        "base_tag": "22.04",
                        "workdir": "/app",
                        "ports": "80",
                    },
                },
            ),
            TemplateInfo(
                name="docker-compose",
                description="Generate a Docker Compose file for multi-container applications",
                category="docker",
                tags=["docker", "compose", "container"],
                output_extension="compose.yaml",
                content="""# {name} - {description}
# Generated by ShellSense AI
version: "{version}"

services:
  {service_name}:
    build: {build_context}
    image: {image_name}
    container_name: {container_name}
    restart: {restart_policy}
    ports:
      - "{ports}"
    environment:
      {env_vars}
    volumes:
      - {volumes}
    networks:
      - {network_name}
    healthcheck:
      test: {healthcheck_test}
      interval: {healthcheck_interval}
      timeout: {healthcheck_timeout}
      retries: {healthcheck_retries}

networks:
  {network_name}:
    driver: {network_driver}
""",
                metadata={
                    "fields": [
                        "name",
                        "description",
                        "version",
                        "service_name",
                        "build_context",
                        "image_name",
                        "container_name",
                        "restart_policy",
                        "ports",
                        "env_vars",
                        "volumes",
                        "network_name",
                        "healthcheck_test",
                        "healthcheck_interval",
                        "healthcheck_timeout",
                        "healthcheck_retries",
                        "network_driver",
                    ],
                    "defaults": {
                        "version": "3.8",
                        "restart_policy": "unless-stopped",
                        "network_driver": "bridge",
                        "healthcheck_interval": "30s",
                        "healthcheck_timeout": "10s",
                        "healthcheck_retries": "3",
                    },
                },
            ),
            TemplateInfo(
                name="nginx-reverse-proxy",
                description="Generate an Nginx reverse proxy configuration",
                category="webserver",
                tags=["nginx", "proxy", "web"],
                output_extension=".conf",
                content="""# {name} - {description}
# Generated by ShellSense AI
server {{
    listen {listen_port}{ssl_section};
    server_name {server_name};

    {ssl_config}

    access_log /var/log/nginx/{name}_access.log;
    error_log /var/log/nginx/{name}_error.log;

    location / {{
        proxy_pass {proxy_pass};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_buffering {proxy_buffering};
        proxy_cache_bypass $http_upgrade;

        {extra_proxy_settings}
    }}

    location /health {{
        access_log off;
        return 200 "OK";
        add_header Content-Type text/plain;
    }}

    {extra_locations}
}}
""",
                metadata={
                    "fields": [
                        "name",
                        "description",
                        "listen_port",
                        "server_name",
                        "proxy_pass",
                        "ssl_section",
                        "ssl_config",
                        "proxy_buffering",
                        "extra_proxy_settings",
                        "extra_locations",
                    ],
                    "defaults": {"listen_port": "80", "proxy_buffering": "off"},
                },
            ),
            TemplateInfo(
                name="apache-vhost",
                description="Generate an Apache VirtualHost configuration",
                category="webserver",
                tags=["apache", "vhost", "web"],
                output_extension=".conf",
                content="""# {name} - {description}
# Generated by ShellSense AI
<VirtualHost *:{listen_port}>
    ServerName {server_name}
    ServerAlias {server_aliases}
    DocumentRoot {document_root}

    <Directory {document_root}>
        Options {directory_options}
        AllowOverride {allow_override}
        Require {require_access}
    </Directory>

    ErrorLog ${{APACHE_LOG_DIR}}/{name}_error.log
    CustomLog ${{APACHE_LOG_DIR}}/{name}_access.log combined

    {ssl_config}

    {extra_config}
</VirtualHost>
""",
                metadata={
                    "fields": [
                        "name",
                        "description",
                        "listen_port",
                        "server_name",
                        "server_aliases",
                        "document_root",
                        "directory_options",
                        "allow_override",
                        "require_access",
                        "ssl_config",
                        "extra_config",
                    ],
                    "defaults": {
                        "listen_port": "80",
                        "directory_options": "Indexes FollowSymLinks",
                        "allow_override": "All",
                        "require_access": "all granted",
                    },
                },
            ),
            TemplateInfo(
                name="ssh-client-config",
                description="Generate an SSH client configuration",
                category="ssh",
                tags=["ssh", "client", "security"],
                output_extension=".conf",
                content="""# {name} - SSH Client Configuration
# Generated by ShellSense AI
Host {host_alias}
    HostName {hostname}
    User {user}
    Port {port}
    IdentityFile {identity_file}
    {extra_options}

# Global settings
Host *
    Protocol 2
    ServerAliveInterval {keepalive_interval}
    ServerAliveCountMax {keepalive_count}
    StrictHostKeyChecking {strict_checking}
    UserKnownHostsFile ~/.ssh/known_hosts
    Compression {compression}
    ForwardAgent {forward_agent}
""",
                metadata={
                    "fields": [
                        "name",
                        "host_alias",
                        "hostname",
                        "user",
                        "port",
                        "identity_file",
                        "extra_options",
                        "keepalive_interval",
                        "keepalive_count",
                        "strict_checking",
                        "compression",
                        "forward_agent",
                    ],
                    "defaults": {
                        "port": "22",
                        "keepalive_interval": "60",
                        "keepalive_count": "3",
                        "strict_checking": "yes",
                        "compression": "yes",
                        "forward_agent": "no",
                    },
                },
            ),
            TemplateInfo(
                name="ssh-server-config",
                description="Generate a secure SSH server configuration",
                category="ssh",
                tags=["ssh", "server", "security"],
                output_extension=".conf",
                content="""# {name} - SSH Server Configuration
# Generated by ShellSense AI
# Place in /etc/ssh/sshd_config.d/{name}.conf

Port {port}
Protocol 2

HostKey /etc/ssh/ssh_host_ed25519_key
HostKey /etc/ssh/ssh_host_rsa_key

{authentication_methods}

PermitRootLogin {permit_root_login}
PubkeyAuthentication yes
PasswordAuthentication {password_auth}
ChallengeResponseAuthentication no
UsePAM yes

LoginGraceTime {login_grace_time}
MaxAuthTries {max_auth_tries}
MaxSessions {max_sessions}
MaxStartups {max_startups}

AllowUsers {allow_users}
DenyUsers {deny_users}

ClientAliveInterval {keepalive_interval}
ClientAliveCountMax {keepalive_count}

X11Forwarding {x11_forwarding}
AllowTcpForwarding {tcp_forwarding}

LogLevel {log_level}
SyslogFacility AUTH
""",
                metadata={
                    "fields": [
                        "name",
                        "port",
                        "authentication_methods",
                        "permit_root_login",
                        "password_auth",
                        "login_grace_time",
                        "max_auth_tries",
                        "max_sessions",
                        "max_startups",
                        "allow_users",
                        "deny_users",
                        "keepalive_interval",
                        "keepalive_count",
                        "x11_forwarding",
                        "tcp_forwarding",
                        "log_level",
                    ],
                    "defaults": {
                        "port": "22",
                        "permit_root_login": "prohibit-password",
                        "password_auth": "no",
                        "login_grace_time": "30",
                        "max_auth_tries": "3",
                        "max_sessions": "10",
                        "max_startups": "10:30:100",
                        "keepalive_interval": "60",
                        "keepalive_count": "3",
                        "x11_forwarding": "no",
                        "tcp_forwarding": "no",
                        "log_level": "VERBOSE",
                    },
                },
            ),
            TemplateInfo(
                name="cron-job",
                description="Generate a cron job entry",
                category="cron",
                tags=["cron", "scheduling", "automation"],
                output_extension=".txt",
                content="""# {name} - {description}
# Generated by ShellSense AI
# Minute Hour DayOfMonth Month DayOfWeek Command
{schedule} {command}

# To install: crontab {name}.txt
# To list:    crontab -l
# To edit:    crontab -e
""",
                metadata={"fields": ["name", "description", "schedule", "command"]},
            ),
            TemplateInfo(
                name="python-script",
                description="Generate a Python automation script",
                category="python",
                tags=["python", "automation", "script"],
                output_extension=".py",
                content="""#!/usr/bin/env python3
\"\"\"{name} - {description}

Generated by ShellSense AI
\"\"\"
import argparse
import logging
import os
import sys
from pathlib import Path

{imports}

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
)
logger = logging.getLogger(__name__)


{classes}


def {main_func}({main_args}) -> int:
    \"\"\"Main function for {name}.\"\"\"
    logger.info("Starting {name}")
    {main_body}
    logger.info("Finished {name}")
    return 0


def setup_argparse() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="{description}")
    parser.add_argument("-v", "--verbose", action="store_true", help="Enable verbose logging")
    {argparse_args}
    return parser


def main() -> None:
    parser = setup_argparse()
    args = parser.parse_args()
    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)
    sys.exit({main_func}(args))


if __name__ == "__main__":
    main()
""",
                metadata={
                    "fields": [
                        "name",
                        "description",
                        "imports",
                        "classes",
                        "main_func",
                        "main_args",
                        "main_body",
                        "argparse_args",
                    ]
                },
            ),
            TemplateInfo(
                name="ansible-playbook",
                description="Generate a basic Ansible playbook",
                category="infrastructure",
                tags=["ansible", "infrastructure", "iac"],
                output_extension=".yaml",
                content="""---
# {name} - {description}
# Generated by ShellSense AI
- name: {playbook_name}
  hosts: {hosts}
  become: {become}
  vars:
    {vars}
  tasks:
    {tasks}
  handlers:
    {handlers}
""",
                metadata={
                    "fields": [
                        "name",
                        "description",
                        "playbook_name",
                        "hosts",
                        "become",
                        "vars",
                        "tasks",
                        "handlers",
                    ],
                    "defaults": {"hosts": "all", "become": "yes"},
                },
            ),
            TemplateInfo(
                name="kubernetes-deployment",
                description="Generate a Kubernetes Deployment YAML",
                category="infrastructure",
                tags=["kubernetes", "k8s", "container"],
                output_extension=".yaml",
                content="""---
# {name} - {description}
# Generated by ShellSense AI
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {deployment_name}
  namespace: {namespace}
  labels:
    app: {app_label}
spec:
  replicas: {replicas}
  selector:
    matchLabels:
      app: {app_label}
  template:
    metadata:
      labels:
        app: {app_label}
    spec:
      containers:
        - name: {container_name}
          image: {image}
          ports:
            - containerPort: {container_port}
          env:
            {env_vars}
          resources:
            requests:
              memory: "{memory_request}"
              cpu: "{cpu_request}"
            limits:
              memory: "{memory_limit}"
              cpu: "{cpu_limit}"
          livenessProbe:
            httpGet:
              path: {health_path}
              port: {container_port}
            initialDelaySeconds: {health_delay}
            periodSeconds: {health_period}
          readinessProbe:
            httpGet:
              path: {health_path}
              port: {container_port}
            initialDelaySeconds: {readiness_delay}
            periodSeconds: {readiness_period}
---
apiVersion: v1
kind: Service
metadata:
  name: {service_name}
  namespace: {namespace}
spec:
  selector:
    app: {app_label}
  ports:
    - protocol: TCP
      port: {service_port}
      targetPort: {container_port}
  type: {service_type}
""",
                metadata={
                    "fields": [
                        "name",
                        "description",
                        "deployment_name",
                        "namespace",
                        "app_label",
                        "replicas",
                        "container_name",
                        "image",
                        "container_port",
                        "env_vars",
                        "memory_request",
                        "cpu_request",
                        "memory_limit",
                        "cpu_limit",
                        "health_path",
                        "health_delay",
                        "health_period",
                        "readiness_delay",
                        "readiness_period",
                        "service_name",
                        "service_port",
                        "service_type",
                    ],
                    "defaults": {
                        "namespace": "default",
                        "replicas": "1",
                        "container_port": "80",
                        "memory_request": "256Mi",
                        "cpu_request": "250m",
                        "memory_limit": "512Mi",
                        "cpu_limit": "500m",
                        "health_path": "/health",
                        "health_delay": "10",
                        "health_period": "15",
                        "readiness_delay": "5",
                        "readiness_period": "10",
                        "service_port": "80",
                        "service_type": "ClusterIP",
                    },
                },
            ),
        ]
        for tpl in builtins:
            self._templates[tpl.name] = tpl

    def register(self, template: TemplateInfo) -> None:
        self._templates[template.name] = template

    def get(self, name: str) -> TemplateInfo | None:
        return self._templates.get(name)

    def list(
        self, category: str | None = None, tag: str | None = None
    ) -> list[TemplateInfo]:
        results = list(self._templates.values())
        if category:
            results = [t for t in results if t.category == category]
        if tag:
            results = [t for t in results if tag in t.tags]
        return results

    def list_categories(self) -> list[str]:
        return sorted(set(t.category for t in self._templates.values()))

    def list_tags(self) -> list[str]:
        return sorted(set(tag for t in self._templates.values() for tag in t.tags))

    def search(self, query: str) -> list[TemplateInfo]:
        q = query.lower()
        results = []
        for t in self._templates.values():
            if (
                q in t.name.lower()
                or q in t.description.lower()
                or q in t.category.lower()
            ):
                results.append(t)
                continue
            if any(q in tag.lower() for tag in t.tags):
                results.append(t)
        return results

    def render(self, template_name: str, **variables: str) -> str | None:
        tpl = self.get(template_name)
        if tpl is None:
            return None
        content = tpl.content
        for key, val in variables.items():
            placeholder = "{" + key + "}"
            content = content.replace(placeholder, val)
        return content

    def remove(self, name: str) -> bool:
        if name in self._templates:
            del self._templates[name]
            return True
        return False

    @property
    def count(self) -> int:
        return len(self._templates)

    def export(self) -> list[dict[str, Any]]:
        return [t.to_dict() for t in self._templates.values()]

    def import_templates(self, data: list[dict[str, Any]]) -> int:
        count = 0
        for item in data:
            try:
                tpl = TemplateInfo(
                    name=item["name"],
                    description=item.get("description", ""),
                    category=item.get("category", "custom"),
                    tags=item.get("tags", []),
                    version=item.get("version", "1.0.0"),
                    output_extension=item.get("output_extension", ".txt"),
                    content=item.get("content", ""),
                    metadata=item.get("metadata", {}),
                )
                self.register(tpl)
                count += 1
            except Exception as e:
                logger.warning("Failed to import template: %s", e)
        return count
