from __future__ import annotations

from typing import Any

from shellsense.automation.generators.bash import GeneratedOutput
from shellsense.automation.templates import TemplateLibrary
from shellsense.utils.logging import get_logger

logger = get_logger(__name__)


class InfrastructureGenerator:
    def __init__(self, templates: TemplateLibrary) -> None:
        self._templates = templates

    def generate_ansible_playbook(
        self,
        name: str = "playbook",
        description: str = "Ansible playbook",
        playbook_name: str = "Main playbook",
        hosts: str = "all",
        become: str = "yes",
        tasks: str = "- name: Ensure package is installed\n  apt:\n    name: nginx\n    state: present",
    ) -> GeneratedOutput:
        content = (
            self._templates.render(
                "ansible-playbook",
                name=name,
                description=description,
                playbook_name=playbook_name,
                hosts=hosts,
                become=become,
                vars="",
                tasks=tasks,
                handlers="",
            )
            or ""
        )
        return GeneratedOutput(
            content=content,
            filename=f"{name}",
            extension=".yaml",
            description=f"Ansible playbook: {description}",
            warnings=["Review before applying with ansible-playbook"],
        )

    def generate_terraform(
        self, name: str = "main", description: str = "Terraform configuration"
    ) -> GeneratedOutput:
        content = f"""# {name} - {description}
# Generated by ShellSense AI
terraform {{
  required_version = ">= 1.0"
  required_providers {{
    local = {{
      source  = "hashicorp/local"
      version = "~> 2.0"
    }}
    random = {{
      source  = "hashicorp/random"
      version = "~> 3.0"
    }}
  }}
}}

# Example resources
resource "local_file" "example" {{
  content  = "Hello from Terraform"
  filename = "${{path.module}}/example.txt"
}}

resource "random_id" "example" {{
  byte_length = 4
}}

output "example_id" {{
  value = random_id.example.hex
  description = "Example random ID"
}}
"""
        return GeneratedOutput(
            content=content,
            filename=f"{name}",
            extension=".tf",
            description=f"Terraform module: {description}",
        )

    def generate_kubernetes(
        self,
        name: str = "app",
        description: str = "Kubernetes deployment",
        deployment_name: str = "myapp",
        image: str = "nginx:alpine",
        container_port: str = "80",
        replicas: str = "3",
    ) -> GeneratedOutput:
        content = (
            self._templates.render(
                "kubernetes-deployment",
                name=name,
                description=description,
                deployment_name=deployment_name,
                namespace="default",
                app_label=name,
                replicas=replicas,
                container_name=name,
                image=image,
                container_port=container_port,
                env_vars="",
                memory_request="256Mi",
                cpu_request="250m",
                memory_limit="512Mi",
                cpu_limit="500m",
                health_path="/health",
                health_delay="10",
                health_period="15",
                readiness_delay="5",
                readiness_period="10",
                service_name=f"{name}-svc",
                service_port="80",
                service_type="ClusterIP",
            )
            or ""
        )
        return GeneratedOutput(
            content=content,
            filename=f"{name}",
            extension=".yaml",
            description=f"Kubernetes manifest for {name}",
            warnings=["Review and customize resource limits"],
        )

    def generate_podman(
        self,
        name: str = "app",
        description: str = "Podman container",
        image: str = "docker.io/library/nginx:alpine",
        ports: str = "8080:80",
        volume: str = "./html:/usr/share/nginx/html:Z",
    ) -> GeneratedOutput:
        content = f"""# {name} - {description}
# Generated by ShellSense AI
# Run with: podman play kube {name}.yaml

# Run container directly:
# podman run -d --name {name} -p {ports} -v {volume} {image}

# Generate systemd service:
# podman generate systemd --name {name} --files
"""
        return GeneratedOutput(
            content=content,
            filename=f"{name}",
            extension=".yaml",
            description=f"Podman configuration for {name}",
        )

    def generate(self, template_name: str, **kwargs: Any) -> GeneratedOutput:
        generators = {
            "ansible": self.generate_ansible_playbook,
            "terraform": self.generate_terraform,
            "kubernetes": self.generate_kubernetes,
            "podman": self.generate_podman,
        }
        gen = generators.get(template_name)
        if gen is None:
            return self.generate_ansible_playbook()
        return gen(**{k: v for k, v in kwargs.items() if k in gen.__code__.co_varnames})
