from __future__ import annotations

from typing import Any

from shellsense.automation.generators.bash import GeneratedOutput
from shellsense.automation.templates import TemplateLibrary
from shellsense.utils.logging import get_logger

logger = get_logger(__name__)


class PythonGenerator:
    def __init__(self, templates: TemplateLibrary) -> None:
        self._templates = templates

    def _render(self, template_name: str, **kwargs: str) -> str:
        return self._templates.render(template_name, **kwargs) or ""

    def generate_script(
        self,
        name: str = "script",
        description: str = "Automation script",
        imports: str = "import os\nimport sys",
        classes: str = "",
        main_func: str = "run",
        main_args: str = "args",
        main_body: str = 'print("Running...")',
        argparse_args: str = 'parser.add_argument("--input", help="Input path")',
    ) -> GeneratedOutput:
        content = self._render(
            "python-script",
            name=name,
            description=description,
            imports=imports,
            classes=classes,
            main_func=main_func,
            main_args=main_args,
            main_body=main_body,
            argparse_args=argparse_args,
        )
        return GeneratedOutput(
            content=content, filename=name, extension=".py", description=description
        )

    def generate_sysadmin(self, name: str = "sysadmin") -> GeneratedOutput:
        content = '''#!/usr/bin/env python3
"""System Administration Utility - {name}

Generated by ShellSense AI
"""
import argparse
import logging
import os
import shutil
import subprocess
import sys

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)


def check_disk_usage(path: str = "/") -> dict:
    usage = shutil.disk_usage(path)
    return {
        "path": path,
        "total_gb": usage.total / (1024**3),
        "used_gb": usage.used / (1024**3),
        "free_gb": usage.free / (1024**3),
        "percent_used": (usage.used / usage.total) * 100,
    }


def check_service(service_name: str) -> bool:
    try:
        r = subprocess.run(
            ["systemctl", "is-active", "--quiet", service_name],
            capture_output=True, timeout=10,
        )
        return r.returncode == 0
    except Exception:
        return False


def main() -> int:
    parser = argparse.ArgumentParser(description="System Administration Utility")
    parser.add_argument("--disk", "-d", metavar="PATH", help="Check disk usage")
    parser.add_argument("--service", "-s", metavar="NAME", help="Check service status")
    parser.add_argument("--verbose", "-v", action="store_true", help="Verbose output")
    args = parser.parse_args()

    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)

    if args.disk:
        usage = check_disk_usage(args.disk)
        logger.info("Disk usage for %s:", usage["path"])
        logger.info("  Total: %.1f GB", usage["total_gb"])
        logger.info("  Used:  %.1f GB (%.1f%%)", usage["used_gb"], usage["percent_used"])
        logger.info("  Free:  %.1f GB", usage["free_gb"])

    if args.service:
        status = check_service(args.service)
        logger.info("Service %s: %s", args.service, "active" if status else "inactive")
        if not status:
            logger.warning("Service %s is not running", args.service)

    return 0


if __name__ == "__main__":
    sys.exit(main())
'''.replace("{name}", name)
        return GeneratedOutput(
            content=content,
            filename=name,
            extension=".py",
            description=f"System administration utility: {name}",
        )

    def generate_log_parser(self, name: str = "log_parser") -> GeneratedOutput:
        content = '''#!/usr/bin/env python3
"""Log Parser - {name}

Generated by ShellSense AI
"""
import argparse
import logging
import re
from collections import Counter
from pathlib import Path

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)

ERROR_PATTERNS = {
    "error": re.compile(r"\\b(error|failed|failure|critical)\\b", re.IGNORECASE),
    "warning": re.compile(r"\\b(warning|warn)\\b", re.IGNORECASE),
    "ip_address": re.compile(r"\\b(?:[0-9]{1,3}\\.){{3}}[0-9]{1,3}\\b"),
    "timestamp": re.compile(r"\\d{{4}}-\\d{{2}}-\\d{{2}}[ T]\\d{{2}}:\\d{{2}}:\\d{{2}}"),
}


def parse_log(filepath: str, pattern: str | None = None) -> dict:
    log_path = Path(filepath)
    if not log_path.exists():
        raise FileNotFoundError(f"Log file not found: {filepath}")

    result = {
        "file": filepath,
        "total_lines": 0,
        "errors": [],
        "warnings": [],
        "ip_counts": Counter(),
        "empty_lines": 0,
    }

    compiled = re.compile(pattern, re.IGNORECASE) if pattern else None

    with open(log_path, errors="ignore") as f:
        for line in f:
            stripped = line.strip()
            result["total_lines"] += 1
            if not stripped:
                result["empty_lines"] += 1
                continue

            if compiled and compiled.search(stripped):
                result["errors"].append(stripped[:200])

            if ERROR_PATTERNS["error"].search(stripped):
                result["errors"].append(stripped[:200])
            if ERROR_PATTERNS["warning"].search(stripped):
                result["warnings"].append(stripped[:200])
            for ip in ERROR_PATTERNS["ip_address"].findall(stripped):
                result["ip_counts"][ip] += 1

    return result


def main() -> int:
    parser = argparse.ArgumentParser(description="Log Parser")
    parser.add_argument("file", help="Path to log file")
    parser.add_argument("--pattern", "-p", help="Custom regex pattern")
    parser.add_argument("--limit", "-l", type=int, default=50, help="Max output lines")
    parser.add_argument("--verbose", "-v", action="store_true")
    args = parser.parse_args()

    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)

    try:
        result = parse_log(args.file, args.pattern)
    except Exception as e:
        logger.error("Failed to parse log: %s", e)
        return 1

    logger.info("Parsed %s:", result["file"])
    logger.info("  Total lines: %d", result["total_lines"])
    logger.info("  Errors found: %d", len(result["errors"]))
    logger.info("  Warnings found: %d", len(result["warnings"]))
    logger.info("  Unique IPs: %d", len(result["ip_counts"]))

    if result["errors"]:
        logger.info("\\nRecent errors (last %d):", args.limit)
        for err in result["errors"][-args.limit:]:
            logger.info("  - %s", err)

    return 0


if __name__ == "__main__":
    exit(main())
'''.replace("{name}", name)
        return GeneratedOutput(
            content=content,
            filename=name,
            extension=".py",
            description=f"Log parser: {name}",
        )

    def generate(self, template_name: str, **kwargs: Any) -> GeneratedOutput:
        generators = {
            "script": self.generate_script,
            "sysadmin": self.generate_sysadmin,
            "log-parser": self.generate_log_parser,
        }
        gen = generators.get(template_name)
        if gen is None:
            return self.generate_script(
                name=kwargs.get("name", "script"),
                description=kwargs.get("description", ""),
            )
        return gen(**{k: v for k, v in kwargs.items() if k in gen.__code__.co_varnames})
