from __future__ import annotations

from typing import Any

from shellsense.automation.generators.bash import GeneratedOutput
from shellsense.automation.templates import TemplateLibrary
from shellsense.utils.logging import get_logger

logger = get_logger(__name__)


class SSHGenerator:
    def __init__(self, templates: TemplateLibrary) -> None:
        self._templates = templates

    def generate_client_config(
        self,
        name: str = "server1",
        host_alias: str = "myserver",
        hostname: str = "server.example.com",
        user: str = "admin",
        port: str = "22",
        identity_file: str = "~/.ssh/id_ed25519",
    ) -> GeneratedOutput:
        content = (
            self._templates.render(
                "ssh-client-config",
                name=name,
                host_alias=host_alias,
                hostname=hostname,
                user=user,
                port=port,
                identity_file=identity_file,
                extra_options="",
                keepalive_interval="60",
                keepalive_count="3",
                strict_checking="yes",
                compression="yes",
                forward_agent="no",
            )
            or ""
        )
        return GeneratedOutput(
            content=content,
            filename=f"ssh_config_{name}",
            extension=".conf",
            description=f"SSH client config for {hostname}",
        )

    def generate_server_config(
        self,
        name: str = "sshd_config",
        port: str = "22",
        permit_root_login: str = "prohibit-password",
        password_auth: str = "no",
        allow_users: str = "",
        deny_users: str = "",
    ) -> GeneratedOutput:
        auth_methods = """# Authentication
PubkeyAuthentication yes
AuthorizedKeysFile .ssh/authorized_keys"""
        content = (
            self._templates.render(
                "ssh-server-config",
                name=name,
                port=port,
                authentication_methods=auth_methods,
                permit_root_login=permit_root_login,
                password_auth=password_auth,
                login_grace_time="30",
                max_auth_tries="3",
                max_sessions="10",
                max_startups="10:30:100",
                allow_users=allow_users or "root",
                deny_users=deny_users or "",
                keepalive_interval="60",
                keepalive_count="3",
                x11_forwarding="no",
                tcp_forwarding="no",
                log_level="VERBOSE",
            )
            or ""
        )
        warnings = ["This is a security-sensitive configuration - review carefully"]
        if password_auth == "yes":
            warnings.append(
                "Password authentication enabled - consider using key-based auth"
            )
        return GeneratedOutput(
            content=content,
            filename=f"{name}",
            extension=".conf",
            description="SSH server configuration",
            warnings=warnings,
        )

    def generate_key_guidance(self) -> GeneratedOutput:
        content = """# SSH Key Generation Guidance
# Generated by ShellSense AI

# ED25519 key (recommended):
ssh-keygen -t ed25519 -a 100 -f ~/.ssh/id_ed25519 -C "your_email@example.com"

# RSA key (fallback):
ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -C "your_email@example.com"

# Copy public key to server:
ssh-copy-id -i ~/.ssh/id_ed25519.pub user@server.example.com

# Or manually:
cat ~/.ssh/id_ed25519.pub | ssh user@server.example.com "mkdir -p ~/.ssh && cat >> ~/.ssh/authorized_keys"

# Test connection:
ssh -i ~/.ssh/id_ed25519 user@server.example.com

# Security recommendations:
# 1. Use ed25519 keys (faster, more secure than RSA)
# 2. Add a passphrase to your private key
# 3. Consider using ssh-agent to cache passphrases
# 4. Disable password authentication after setting up keys
# 5. Use different keys for different services
# 6. Rotate keys periodically
# 7. Use SSH certificates for larger deployments
"""
        return GeneratedOutput(
            content=content,
            filename="ssh_key_guidance",
            extension=".md",
            description="SSH key generation guidance",
        )

    def generate(self, template_name: str, **kwargs: Any) -> GeneratedOutput:
        generators = {
            "client": self.generate_client_config,
            "server": self.generate_server_config,
            "key-guidance": self.generate_key_guidance,
        }
        gen = generators.get(template_name)
        if gen is None:
            return self.generate_client_config()
        return gen(**{k: v for k, v in kwargs.items() if k in gen.__code__.co_varnames})
