from __future__ import annotations

from typing import Any

from shellsense.automation.generators.bash import GeneratedOutput
from shellsense.automation.templates import TemplateLibrary
from shellsense.utils.logging import get_logger

logger = get_logger(__name__)


class WebServerGenerator:
    def __init__(self, templates: TemplateLibrary) -> None:
        self._templates = templates

    def generate_nginx_reverse_proxy(
        self,
        name: str = "proxy",
        description: str = "Reverse proxy",
        server_name: str = "example.com",
        proxy_pass: str = "http://localhost:8000",
        listen_port: str = "443",
        ssl: bool = True,
    ) -> GeneratedOutput:
        ssl_section = " ssl" if ssl else ""
        ssl_config = ""
        if ssl:
            ssl_config = f"""    ssl_certificate /etc/nginx/ssl/{name}.crt;
    ssl_certificate_key /etc/nginx/ssl/{name}.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;"""
        content = (
            self._templates.render(
                "nginx-reverse-proxy",
                name=name,
                description=description,
                listen_port=listen_port,
                ssl_section=ssl_section,
                server_name=server_name,
                ssl_config=ssl_config,
                proxy_pass=proxy_pass,
                proxy_buffering="off",
                extra_proxy_settings="",
                extra_locations="",
            )
            or ""
        )
        warnings = []
        if ssl:
            warnings.append(f"SSL certificates required at /etc/nginx/ssl/{name}.crt")
        return GeneratedOutput(
            content=content,
            filename=f"{name}",
            extension=".conf",
            description=f"Nginx reverse proxy for {server_name}",
            warnings=warnings,
        )

    def generate_nginx_static(
        self,
        name: str = "static",
        description: str = "Static site",
        server_name: str = "example.com",
        root: str = "/var/www/html",
        listen_port: str = "80",
    ) -> GeneratedOutput:
        content = f"""# {name} - {description}
# Generated by ShellSense AI
server {{
    listen {listen_port};
    server_name {server_name};
    root {root};
    index index.html index.htm;

    access_log /var/log/nginx/{name}_access.log;
    error_log /var/log/nginx/{name}_error.log;

    location / {{
        try_files $uri $uri/ =404;
    }}

    location ~ \\.php$ {{
        fastcgi_pass unix:/var/run/php/php8.1-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }}

    location ~ /\\. {{
        deny all;
    }}
}}
"""
        return GeneratedOutput(
            content=content,
            filename=f"{name}",
            extension=".conf",
            description=f"Nginx static site for {server_name}",
        )

    def generate_nginx_load_balancer(
        self,
        name: str = "lb",
        description: str = "Load balancer",
        server_name: str = "example.com",
        upstreams: str = "server 10.0.0.1:8000; server 10.0.0.2:8000;",
    ) -> GeneratedOutput:
        content = f"""# {name} - {description}
# Generated by ShellSense AI
upstream backend {{
    least_conn;
    {upstreams}
}}

server {{
    listen 80;
    server_name {server_name};

    location / {{
        proxy_pass http://backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }}

    location /health {{
        return 200 "OK";
        add_header Content-Type text/plain;
    }}
}}
"""
        return GeneratedOutput(
            content=content,
            filename=f"{name}",
            extension=".conf",
            description=f"Nginx load balancer for {server_name}",
        )

    def generate_apache_vhost(
        self,
        name: str = "site",
        description: str = "Apache virtual host",
        server_name: str = "example.com",
        document_root: str = "/var/www/html",
        listen_port: str = "80",
        ssl: bool = False,
    ) -> GeneratedOutput:
        server_aliases = f"www.{server_name}"
        ssl_config = ""
        if ssl:
            ssl_config = f"""    SSLEngine on
    SSLCertificateFile /etc/ssl/certs/{name}.crt
    SSLCertificateKeyFile /etc/ssl/private/{name}.key"""
        content = (
            self._templates.render(
                "apache-vhost",
                name=name,
                description=description,
                listen_port=listen_port,
                server_name=server_name,
                server_aliases=server_aliases,
                document_root=document_root,
                directory_options="Indexes FollowSymLinks",
                allow_override="All",
                require_access="all granted",
                ssl_config=ssl_config,
                extra_config="",
            )
            or ""
        )
        warnings = []
        if ssl:
            warnings.append("SSL certificates required")
        return GeneratedOutput(
            content=content,
            filename=f"{name}",
            extension=".conf",
            description=f"Apache vhost for {server_name}",
            warnings=warnings,
        )

    def generate(self, template_name: str, **kwargs: Any) -> GeneratedOutput:
        generators = {
            "nginx-reverse-proxy": self.generate_nginx_reverse_proxy,
            "nginx-static": self.generate_nginx_static,
            "nginx-load-balancer": self.generate_nginx_load_balancer,
            "apache-vhost": self.generate_apache_vhost,
        }
        gen = generators.get(template_name)
        if gen is None:
            return self.generate_nginx_reverse_proxy()
        return gen(**{k: v for k, v in kwargs.items() if k in gen.__code__.co_varnames})
